remove block only
Signed-off-by: Dongsheng Yang <yangds.fnst@cn.fujitsu.com>

diff --git a/common/config b/common/config
--- a/common/config
+++ b/common/config
@@ -465,11 +465,11 @@ get_next_config() {
 		exit 1
 	fi
 
-	echo $TEST_DEV | grep -qE ":|//" > /dev/null 2>&1
-	if [ ! -b "$TEST_DEV" -a "$?" != "0" ]; then
-		echo "common/config: Error: \$TEST_DEV ($TEST_DEV) is not a block device or a network filesystem"
-		exit 1
-	fi
+	#echo $TEST_DEV | grep -qE ":|//" > /dev/null 2>&1
+	#if [ ! -b "$TEST_DEV" -a "$?" != "0" ]; then
+	#	echo "common/config: Error: \$TEST_DEV ($TEST_DEV) is not a block device or a network filesystem"
+	#	exit 1
+	#fi
 
 	if [ ! -d "$TEST_DIR" ]; then
 		echo "common/config: Error: \$TEST_DIR ($TEST_DIR) is not a directory"
@@ -478,21 +478,21 @@ get_next_config() {
 
 	# a btrfs tester will set only SCRATCH_DEV_POOL, we will put first of its dev
 	# to SCRATCH_DEV and rest to SCRATCH_DEV_POOL to maintain the backward compatibility
-	if [ ! -z "$SCRATCH_DEV_POOL" ]; then
-		if [ ! -z "$SCRATCH_DEV" ]; then
-			echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) should be unset when \$SCRATCH_DEV_POOL ($SCRATCH_DEV_POOL) is set"
-			exit 1
-		fi
-		SCRATCH_DEV=`echo $SCRATCH_DEV_POOL | awk '{print $1}'`
-		export SCRATCH_DEV
-		export SCRATCH_DEV_NOT_SET=true
-	fi
+	#if [ ! -z "$SCRATCH_DEV_POOL" ]; then
+	#	if [ ! -z "$SCRATCH_DEV" ]; then
+	#		echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) should be unset when \$SCRATCH_DEV_POOL ($SCRATCH_DEV_POOL) is set"
+	#		exit 1
+	#	fi
+	#	SCRATCH_DEV=`echo $SCRATCH_DEV_POOL | awk '{print $1}'`
+	#	export SCRATCH_DEV
+	#	export SCRATCH_DEV_NOT_SET=true
+	#fi
 
-	echo $SCRATCH_DEV | grep -qE ":|//" > /dev/null 2>&1
-	if [ ! -z "$SCRATCH_DEV" -a ! -b "$SCRATCH_DEV" -a "$?" != "0" ]; then
-		echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) is not a block device or a network filesystem"
-		exit 1
-	fi
+	#echo $SCRATCH_DEV | grep -qE ":|//" > /dev/null 2>&1
+	#if [ ! -z "$SCRATCH_DEV" -a ! -b "$SCRATCH_DEV" -a "$?" != "0" ]; then
+	#	echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) is not a block device or a network filesystem"
+	#	exit 1
+	#fi
 
 	if [ ! -z "$SCRATCH_MNT" -a ! -d "$SCRATCH_MNT" ]; then
 		echo "common/config: Error: \$SCRATCH_MNT ($SCRATCH_MNT) is not a directory"
